import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../../styles/detail.module.css";


export default function PokemonDetail({ pokemon }) {
    if (!pokemon) {
        return <div>fetching...</div>;
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>{pokemon.name}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}> {pokemon.name} </h1>
                <div>
                    <Image
                        src={pokemon.sprites.front_default}
                        alt={pokemon.name}
                        width={400}
                        height={400}
                    />
                </div>

                {/*info about the pokemon*/}
                <div className={styles.info}>
                    <h2>Details</h2>
                    <p> ID: {pokemon.id}</p>
                    <p>Weight: {pokemon.weight/ 10 } </p>
                    <p>Height: {pokemon.height / 10} </p>


                    <h2>Types</h2>
                    <div className={styles.types}>
                        {pokemon.types.map(type => (
                            <span key={type.type.name} className={styles.type}>
                                {type.type.name}
                            </span>
                        ))}
                    </div>


                    <h2>Abilities</h2>
                    <ul className={styles.abilities}>
                        {pokemon.abilities.map(ability => (
                            <li key={ability.ability.name}>
                                {ability.ability.name}
                                {ability.is_hidden && " (Hidden)"}
                            </li>
                        ))}
                    </ul>

                    <Link href = "/public" className={styles.backButton}>
                        Back to Pokedex
                    </Link>

                </div>
            </main>

        </div>

    );
}


export async function getStaticPaths() {
    const paths = [];
    for (let i = 1; i <= 151; i++) {
        paths.push({
            params: {id: i.toString()}
        });
    }

    return {
        paths,
        fallback: false,
    };
}

// Fetch data for each Pokemon
export async function getStaticProps({ params }) {
    const res = await fetch(`https://pokeapi.co/api/v2/pokemon/${params.id}`);
    const pokemon = await res.json();
    return {
        props: {
            pokemon,
        },
    };
}