import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/home.module.css";


export default function Home({ pokemons } ){
    return (
        <div className={styles.container}>
            <Head>
                <title>Pokedex</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}> Poke Monster DB </h1>

                <div className={styles.grid}>
                    {pokemons.map(pokemon => (
                        <Link href={`/monsters/${pokemon.id}`} key={pokemon.id} className={styles.card} >
                            <div className={styles.card}>
                                {pokemon.sprites?.front_default ?(
                                <Image
                                    src={pokemon.sprites.font_default}
                                    alt={pokemon.name}
                                    width={400}
                                    height={400} />
                                ) : (<p>No Image available</p>)
                                }
                                <h2>{pokemon.name}</h2>
                                <p>#{pokemon.id}</p>
                                <p>Height: {pokemon.height}</p>
                                <p>Weight: {pokemon.weight}</p>
                            </div>
                        </Link>
                    ))}
                </div>
            </main>
        </div>
    );
}

export async function getStaticProps() {
    const poke =[]
    for (let i = 1; i <= 151; i++) {
        const res = await fetch(`https://pokeapi.co/api/v2/pokemon/${i}`);
        const pokemon = await res.json();
        poke.push(pokemon);
    }

    return {
        props: {
            pokemons: poke,
        },
    }
}